### ISSUE TITLE
Podfile Missing

### ISSUE THREAD

**Issue by wellkunnected** [mvitolo/Emoji8Ball#1]
Trying to build this code and there is no podfile.

**Comment by mvitolo** [comment]
https://github.com/mvitolo/Emoji8Ball/blob/master/Podfile

what do you mean?

**Comment by wellkunnected** [comment]
Whenever a pod install is required on an app it usually includes a folder
within the project called "pods". Without this the app wont even build.
When I open your app, the pods file is in red which is an easy indication
that the pods folder is missing. It includes the pod install file and
podspec but no pods folder. Have a look yourself.

On Tue, Feb 2, 2016 at 9:55 AM, Matteo Vitolo notifications@github.com
wrote:

> https://github.com/mvitolo/Emoji8Ball/blob/master/Podfile
> 
> what do you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mvitolo/Emoji8Ball/issues/1#issuecomment-178614959.

## 

Founded Well Kunnected, Inc 2010

**Comment by mvitolo** [comment]
if you run pod install you will download them automatically...

HTH

**Comment by wellkunnected** [comment]
I attached a screenshot of my issue. Notice how this app file includes a folder for the Pods? This is what I mean. The app wont build as it's missing the pods folder.
![screen shot 2016-02-02 at 11 42 10 am](https://cloud.githubusercontent.com/assets/15697545/12756536/29d24caa-c9a2-11e5-86de-12031ec11a35.png)

**Comment by wellkunnected** [comment]
After running pod install, here's the error I'm receiving. Says there is no
such file.

On Tue, Feb 2, 2016 at 10:48 AM, Matteo Vitolo notifications@github.com
wrote:

> if you run pod install you will download them automatically...
> 
> HTH
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mvitolo/Emoji8Ball/issues/1#issuecomment-178648603.

## 

Founded Well Kunnected, Inc 2010

**Comment by mvitolo** [comment]
so I have just compiled it from scratch
here my commands

`$ git clone https://github.com/mvitolo/Emoji8Ball.git` 
`$ cd Emoji8Ball/`
`$ pod install`
`$ open Emoji8Ball.xcworkspace/`

compiling with no issue...

HTH

**Comment by wellkunnected** [comment]
Sorry about the empty message! So I followed all of your instructions and
it did clone the project but now I'm getting that the "sandbox is not in
sync with the podfile" and I've clearly run pod install. Not sure what I'm
doing wrong, but I really like the idea of the project and want to play
around with it a bit!

On Tue, Feb 2, 2016 at 12:09 PM, Armani Rouse armanirouse@gmail.com wrote:

> On Tue, Feb 2, 2016 at 11:58 AM, Matteo Vitolo notifications@github.com
> wrote:
> 
> > so I have just compiled it from scratch
> > here my commands
> > 
> > $ git clone https://github.com/mvitolo/Emoji8Ball.git
> > $ cd Emoji8Ball/
> > $ pod install
> > $ open Emoji8Ball.xcworkspace/
> > 
> > compiling with no issue...
> > 
> > HTH
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/mvitolo/Emoji8Ball/issues/1#issuecomment-178686238.
> 
> ## 
> 
> Founded Well Kunnected, Inc 2010

## 

Founded Well Kunnected, Inc 2010

**Comment by mvitolo** [comment]
http://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res
